# Generated by Django 2.1.14 on 2019-12-05 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('namo_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='city_availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'City Availabilities',
            },
        ),
        migrations.CreateModel(
            name='promo_code',
            fields=[
                ('promo_code_id', models.AutoField(primary_key=True, serialize=False)),
                ('promo_code', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('subtitle', models.CharField(blank=True, max_length=50)),
                ('terms', models.CharField(blank=True, max_length=200)),
                ('image', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='promotions',
            fields=[
                ('promotion_code_id', models.AutoField(primary_key=True, serialize=False)),
                ('promotion_code', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('subtitle', models.CharField(blank=True, max_length=50)),
                ('terms', models.CharField(blank=True, max_length=200)),
                ('image', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Promotions',
            },
        ),
        migrations.CreateModel(
            name='saved_location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('longitude', models.FloatField(blank=True, default=None, null=True)),
                ('latitude', models.FloatField(blank=True, default=None, null=True)),
                ('location', models.CharField(max_length=1000)),
                ('complete_address', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='namo_user.namo_user')),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('icon', models.CharField(blank=True, max_length=300)),
                ('card_image', models.CharField(blank=True, max_length=300)),
                ('tagline', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='namo_services.services')),
            ],
        ),
        migrations.AddField(
            model_name='city_availability',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='namo_services.services'),
        ),
        migrations.AlterUniqueTogether(
            name='city_availability',
            unique_together={('service_type', 'city', 'state')},
        ),
    ]
