# Generated by Django 2.1.14 on 2019-12-06 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namo_user', '0001_initial'),
        ('namo_services', '0002_auto_20191206_0848'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('driver', 'vehicle_number')},
        ),
    ]
