# Generated by Django 2.1.14 on 2019-12-06 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('namo_services', '0003_auto_20191206_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='namo_user.driver', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together=set(),
        ),
    ]
