# Generated by Django 2.1.14 on 2020-01-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namo_services', '0004_auto_20191206_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='fixed_amount',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='services',
            name='rate',
            field=models.IntegerField(default=8),
        ),
    ]
