# Generated by Django 2.1.14 on 2019-12-05 08:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('namo_user', '0001_initial'),
        ('namo_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('booking_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pickup_location_longitude', models.FloatField(blank=True, default=None, null=True)),
                ('pickup_location_latitude', models.FloatField(blank=True, default=None, null=True)),
                ('drop_location_longitude', models.FloatField(blank=True, default=None, null=True)),
                ('drop_location_latitude', models.FloatField(blank=True, default=None, null=True)),
                ('otp', models.CharField(max_length=10)),
                ('varified', models.BooleanField(default=False)),
                ('base_fare', models.FloatField(blank=True, default=None, null=True)),
                ('final_amount', models.FloatField(blank=True, default=None, null=True)),
                ('trip_status', models.CharField(choices=[('ongoing', 'Ongoing Trip'), ('cancled', 'Trip is Cancled'), ('completed', 'Trip is Completed')], default='ongoing', max_length=32)),
                ('payement_mode', models.CharField(default='Cash', max_length=40)),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='namo_user.namo_user')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='namo_user.driver')),
                ('service_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='namo_services.services')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='namo_services.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='ride_history',
            fields=[
                ('ride_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_fare', models.CharField(max_length=50)),
                ('pickup_location_longitude', models.FloatField(blank=True, default=None, null=True)),
                ('pickup_location_latitude', models.FloatField(blank=True, default=None, null=True)),
                ('drop_location_longitude', models.FloatField(blank=True, default=None, null=True)),
                ('drop_location_latitude', models.FloatField(blank=True, default=None, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='namo_user.namo_user')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='namo_user.driver')),
            ],
        ),
    ]
