# Generated by Django 2.1.14 on 2019-12-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namo_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='trip_status',
            field=models.CharField(choices=[('ongoing', 'Ongoing Trip'), ('cancelled', 'Trip is cancelled'), ('completed', 'Trip is Completed')], default='ongoing', max_length=32),
        ),
    ]
