# Generated by Django 2.1.14 on 2019-12-23 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namo_booking', '0002_auto_20191205_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='varified',
            new_name='verified',
        ),
    ]
