# Generated by Django 2.1.14 on 2019-12-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namo_booking', '0003_auto_20191223_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='current_debt_amount',
            field=models.IntegerField(default=0),
        ),
    ]
