# Generated by Django 2.1.14 on 2019-12-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namo_booking', '0004_booking_current_debt_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='current_debt_amount',
            new_name='total_distance_travelled',
        ),
    ]
