# Generated by Django 2.1.14 on 2019-12-30 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namo_booking', '0005_auto_20191224_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='payement_mode',
            new_name='payment_mode',
        ),
    ]
