# Generated by Django 2.1.14 on 2019-12-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namo_booking', '0006_auto_20191230_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('details', models.CharField(blank=True, max_length=500)),
                ('discount_percent', models.IntegerField(default=0)),
                ('maximum_discount', models.IntegerField(default=0)),
                ('used_count', models.IntegerField(default=0)),
                ('max_limit', models.IntegerField(default=0)),
            ],
        ),
    ]
