# Generated by Django 2.1.14 on 2020-01-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namo_booking', '0007_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rating',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='review',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
