# Generated by Django 2.1.14 on 2020-01-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namo_booking', '0008_auto_20200101_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
