# Generated by Django 2.1.14 on 2020-01-02 10:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('namo_user', '0003_auto_20200102_1056'),
        ('namo_services', '0004_auto_20191206_0908'),
        ('namo_booking', '0009_auto_20200102_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='ride_later_booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('pickup_location_longitude', models.FloatField(default=None)),
                ('pickup_location_latitude', models.FloatField(default=None)),
                ('drop_location_longitude', models.FloatField(default=None)),
                ('drop_location_latitude', models.FloatField(default=None)),
                ('payment_mode', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('Processed', 'Processed')], default='pending', max_length=32)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='namo_user.namo_user')),
                ('service_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='namo_services.services')),
            ],
        ),
    ]
