# Generated by Django 2.1.14 on 2020-01-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namo_booking', '0010_ride_later_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride_later_booking',
            name='id',
        ),
        migrations.AddField(
            model_name='ride_later_booking',
            name='booking_id',
            field=models.CharField(default='KVRFPILR', max_length=50, primary_key=True, serialize=False),
        ),
    ]
