# Generated by Django 2.1.14 on 2020-01-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namo_booking', '0012_auto_20200107_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride_later_booking',
            name='booking_id',
            field=models.CharField(default='XSUT4W9W', max_length=50, primary_key=True, serialize=False),
        ),
    ]
