# Generated by Django 2.1.14 on 2020-01-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namo_booking', '0013_auto_20200107_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride_later_booking',
            name='booking_id',
            field=models.CharField(default='5C4X22G0', max_length=50, primary_key=True, serialize=False),
        ),
    ]
