# Generated by Django 2.1.14 on 2019-12-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='driver',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], default='1', max_length=9)),
                ('phone_number', models.CharField(max_length=13, unique=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('licence_number', models.CharField(max_length=50)),
                ('photo', models.CharField(blank=True, max_length=300)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('number_of_trips', models.IntegerField(blank=True, default=0)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('current_debt_amount', models.IntegerField(default=0)),
                ('pan_card', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='namo_user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], default='1', max_length=9)),
                ('phone_number', models.CharField(max_length=13, unique=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('photo', models.CharField(blank=True, max_length=300)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('login_type', models.CharField(choices=[('1', 'phone'), ('2', 'gmail'), ('3', 'Facebook')], default='1', max_length=10)),
            ],
        ),
    ]
