# Generated by Django 2.1.14 on 2020-01-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namo_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='rating',
        ),
        migrations.AddField(
            model_name='driver',
            name='five_stars',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='four_stars',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='one_stars',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='three_stars',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='two_stars',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
