# Generated by Django 2.1.14 on 2020-01-02 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namo_user', '0002_auto_20200102_0619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Driver', 'verbose_name_plural': 'Drivers'},
        ),
        migrations.AlterModelOptions(
            name='namo_user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
