# Generated by Django 2.1.14 on 2020-01-07 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namo_user', '0003_auto_20200102_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='namo_user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 7, 13, 18, 20, 251528)),
        ),
    ]
