# Generated by Django 2.1.14 on 2020-01-07 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namo_user', '0004_namo_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='availability',
            field=models.CharField(choices=[('available', 'available'), ('busy', 'busy')], default='available', max_length=32),
        ),
        migrations.AlterField(
            model_name='namo_user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 7, 14, 20, 1, 758037)),
        ),
    ]
