# Generated by Django 2.1.14 on 2020-01-20 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namo_user', '0005_auto_20200107_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namo_user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 20, 12, 28, 49, 926850)),
        ),
    ]
